build:
  image: debian:sid
  stage: build
  before_script:
    - apt-get update
    - apt-get install -y build-essential cmake libpng-dev file
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make -j4
    - make package
  artifacts:
    paths: 
      - build/*.deb