build:
  image: debian:buster
  stage: build
  before_script:
    - apt-get update > /dev/null
    - apt-get install -y build-essential cmake libpng-dev file > /dev/null
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make -j4
    - make package
  artifacts:
    paths: 
      - build/*.deb